# Generated by Django 3.1.2 on 2020-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='suggestionmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
