# Generated by Django 3.1.2 on 2020-12-01 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='suggestionmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
