# Generated by Django 3.1.2 on 2020-12-01 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionmodel',
            name='likes',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
