# Generated by Django 3.1.2 on 2020-12-08 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_auto_20201201_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
