# Generated by Django 3.1.2 on 2020-12-08 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_auto_20201208_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
