# Generated by Django 3.1.2 on 2020-12-16 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0019_auto_20201216_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='likes',
            field=models.ManyToManyField(related_name='z', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
